
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'

# Theme
set -g @tmux-gruvbox 'dark256'

# Status bar
set -g @tmux-gruvbox-statusbar-alpha 'true'
set -g @tmux-gruvbox-left-status-a '#S'

# "#(date) 
set -g @tmux-gruvbox-right-status-x ' '
set -g @tmux-gruvbox-right-status-y '%m/%d %I:%M'
set -g @tmux-gruvbox-right-status-z ' '

set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
run '~/.config/tmux/plugins/tpm/tpm'

set -g status 2
set -g status-format[1] "#(tmux show-env SSH_IP | cut -d= -f2-)"

## Titles
set -g allow-rename off
set -g automatic-rename off

# Options
set -g mouse on
## Set index to 1 based
set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "tmux-256color"
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g allow-passthrough on
set -g renumber-windows on

## Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 5
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
setw -g aggressive-resize on
set -g set-clipboard on

set-option -g default-shell /bin/zsh


## Keybinds

### Set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Set vi-mode
#set-window-option -g mode-keys vi
#bind-key -T copy-mode-vi v send-keys -X begin-selection
#bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
#bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind [ split-window -h -c "#{pane_current_path}"
bind ] split-window -v -c "#{pane_current_path}"

bind -n C-] next-window
bind -n C-[ previous-window
bind -n M-] switch-client -n
bind -n M-[ switch-client -p

bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D

bind q kill-pane
bind Q kill-window

bind-key -r ? list-keys -aN

unbind n
bind n command-prompt -p "New Session Name:" "new-session -A -d -s '%1' ;\ switch-client -t '%1'"

bind y run-shell "~/.zsh/functions/yazi-cd"
bind g display-popup -d '#{pane_current_path}' -h 95% -w 95% -E "zsh -f -c 'source ~/.zshenv; lazygit'"


bind j display-popup -E -w 80% -h 60% \
  "tmux list-panes -a -F '#S:#I.#P | #{pane_current_command} | #{pane_current_path}' | \
  fzf --header 'Jump to Pane' --reverse \
      --preview 'tmux capture-pane -ept \$(echo {} | cut -d\" \" -f1) | tail -n \${FZF_PREVIEW_LINES}' \
      --preview-window 'bottom:70%:border-top' | \
  cut -d' ' -f1 | xargs tmux switch-client -t"


tmux_config="$HOME/.config/tmux/tmux.conf"
bind-key R run-shell " \
                tmux source-file ${tmux_config} > /dev/null; \
                tmux display-message 'Sourced ${tmux_config}!'"
